"""
Import all models into this package
"""

from pjecz_hercules_cli_typer.models.autoridades import Autoridad
from pjecz_hercules_cli_typer.models.distritos import Distrito
from pjecz_hercules_cli_typer.models.edictos import Edicto
from pjecz_hercules_cli_typer.models.fin_vales import FinVale
from pjecz_hercules_cli_typer.models.inv_custodias import InvCustodia
from pjecz_hercules_cli_typer.models.inv_equipos import InvEquipo
from pjecz_hercules_cli_typer.models.inv_marcas import InvMarca
from pjecz_hercules_cli_typer.models.inv_modelos import InvModelo
from pjecz_hercules_cli_typer.models.listas_de_acuerdos import ListaDeAcuerdo
from pjecz_hercules_cli_typer.models.materias import Materia
from pjecz_hercules_cli_typer.models.materias_tipos_juicios import MateriaTipoJuicio
from pjecz_hercules_cli_typer.models.ofi_documentos import OfiDocumento
from pjecz_hercules_cli_typer.models.roles import Rol
from pjecz_hercules_cli_typer.models.sentencias import Sentencia
from pjecz_hercules_cli_typer.models.soportes_tickets import SoporteTicket
from pjecz_hercules_cli_typer.models.usuarios import Usuario
from pjecz_hercules_cli_typer.models.usuarios_roles import UsuarioRol
